node scripts/create-line-items.js --channel A --platform D --position SIDEBAR --region USA --partner SOVRN && \
node scripts/create-line-items.js --channel A --platform D --position SIDERAIL --region USA --partner SOVRN && \
node scripts/create-line-items.js --channel A --platform D --position SIDEBAR2 --region USA --partner SOVRN && \
node scripts/create-line-items.js --channel A --platform D --position CONTENT --region USA --partner SOVRN && \
node scripts/create-line-items.js --channel A --platform D --position FOOTER --region USA --partner SOVRN && \
node scripts/create-line-items.js --channel A --platform D --position HEADER --region USA --partner SOVRN && \
node scripts/create-line-items.js --channel A --platform D --position SIDEBAR --region INT --partner SOVRN && \
node scripts/create-line-items.js --channel A --platform D --position SIDERAIL --region INT --partner SOVRN && \
node scripts/create-line-items.js --channel A --platform D --position SIDEBAR2 --region INT --partner SOVRN && \
node scripts/create-line-items.js --channel A --platform D --position CONTENT --region INT --partner SOVRN && \
node scripts/create-line-items.js --channel A --platform D --position FOOTER --region INT --partner SOVRN && \
node scripts/create-line-items.js --channel A --platform D --position HEADER --region INT --partner SOVRN && \
node scripts/create-line-items.js --channel B --platform D --position SIDEBAR --region USA --partner SOVRN && \
node scripts/create-line-items.js --channel B --platform D --position SIDERAIL --region USA --partner SOVRN && \
node scripts/create-line-items.js --channel B --platform D --position SIDEBAR2 --region USA --partner SOVRN && \
node scripts/create-line-items.js --channel B --platform D --position CONTENT --region USA --partner SOVRN && \
node scripts/create-line-items.js --channel B --platform D --position FOOTER --region USA --partner SOVRN && \
node scripts/create-line-items.js --channel B --platform D --position HEADER --region USA --partner SOVRN && \
node scripts/create-line-items.js --channel B --platform D --position SIDEBAR --region INT --partner SOVRN && \
node scripts/create-line-items.js --channel B --platform D --position SIDERAIL --region INT --partner SOVRN && \
node scripts/create-line-items.js --channel B --platform D --position SIDEBAR2 --region INT --partner SOVRN && \
node scripts/create-line-items.js --channel B --platform D --position CONTENT --region INT --partner SOVRN && \
node scripts/create-line-items.js --channel B --platform D --position FOOTER --region INT --partner SOVRN && \
node scripts/create-line-items.js --channel B --platform D --position HEADER --region INT --partner SOVRN && \
node scripts/create-line-items.js --channel A --platform M --position CONTENT --region USA --partner SOVRN && \
node scripts/create-line-items.js --channel A --platform M --position HEADER --region USA --partner SOVRN && \
node scripts/create-line-items.js --channel A --platform M --position ADHESION --region USA --partner SOVRN && \
node scripts/create-line-items.js --channel A --platform M --position MIDDLE --region USA --partner SOVRN && \
node scripts/create-line-items.js --channel A --platform M --position CONTENT --region INT --partner SOVRN && \
node scripts/create-line-items.js --channel A --platform M --position HEADER --region INT --partner SOVRN && \
node scripts/create-line-items.js --channel A --platform M --position ADHESION --region INT --partner SOVRN && \
node scripts/create-line-items.js --channel A --platform M --position MIDDLE --region INT --partner SOVRN && \
node scripts/create-line-items.js --channel B --platform M --position CONTENT --region USA --partner SOVRN && \
node scripts/create-line-items.js --channel B --platform M --position HEADER --region USA --partner SOVRN && \
node scripts/create-line-items.js --channel B --platform M --position ADHESION --region USA --partner SOVRN && \
node scripts/create-line-items.js --channel B --platform M --position MIDDLE --region USA --partner SOVRN && \
node scripts/create-line-items.js --channel B --platform M --position CONTENT --region INT --partner SOVRN && \
node scripts/create-line-items.js --channel B --platform M --position HEADER --region INT --partner SOVRN && \
node scripts/create-line-items.js --channel B --platform M --position ADHESION --region INT --partner SOVRN && \
node scripts/create-line-items.js --channel B --platform M --position MIDDLE --region INT --partner SOVRN && \
echo
